name: ${project.name}
author: milkwalk, Airee
version: ${project.version}
main: cz.dubcat.xpboost.XPBoostMain
commands:
    xpboost:
        description: Main command.
        aliases: [xpb]
        permission: xpboost.use
        permission-message: '§c§lERROR: §7No permission.'
permissions:
    xpboost.use:
        description: Allows you to use the plugin
        default: op
    xpboost.admin:
        description: Allows you to use the admin commands
        default: op
depend: [Vault]
softdepend: [Vault,SkillAPI,RPGme,BossBarAPI,Heroes,PlaceholderAPI,MVdWPlaceholderAPI]